import React from 'react'
import ArticleItem from '../_components/articles/ArticleItem'
import { IArticleProps } from '@/types/types'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "articles",
  description: "Generated by create next app",
};
const page = async () => {
  const response = await fetch('http://localhost:3000/api/articles', {
    cache: "no-store"
  })

  if(!response.ok){
    throw new Error("Failed to fetch articles")
  }
  const articles: IArticleProps[] = await response.json()
  return (
    <div className="mx-auto max-w-screen-xl px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
        {articles.map((item) => <ArticleItem key={item.id} article={item}/>)}
      </div>
    </div>
  )
}

export default page
